// Code generated by jtd-codegen for TypeScript v0.2.1

export interface Order {
  deliveryFee: number;
  fulfilmentDate: string;
  fulfilmentTime: string;
  isEditable: boolean;
  method: string;
  orderDate: string;
  orderId: number;
  prefix: string;
  status: string;
  total: number;
}
