// Code generated by jtd-codegen for TypeScript v0.2.1

import { ShoppingListItem } from "../ShoppingListItems";

export interface ShoppingList {
  description: string | null;
  id: string;
  name: string;
  row_created_timestamp: string;
  userfields?: Record<string, string> | null;
}

export type ShoppingListDetail = ShoppingList & { items: ShoppingListItem[] };
