// Code generated by jtd-codegen for TypeScript v0.2.1

import { Unknown } from "@gt/jtd/infer";

export interface OrderDetailsBreadcrumb {
  aisle?: unknown;
  department?: unknown;
  dynamicGroup?: unknown;
  productGroup?: unknown;
  shelf?: unknown;
}

export interface OrderDetailsContextAdvancedSettingsResponse {
  allowBannerRotation: boolean;
  itemLevelSubstitution: boolean;
  showHaveYouForgotten: boolean;
}

export interface OrderDetailsContextBasketTotals {
  bagFees: string;
  deliveryFees: string;
  eligibilityForDeliverySubscriptionDiscount: string;
  savings: string;
  subtotal: string;
  totalIncludingDeliveryFees: string;
  totalItems: number;
}

export interface OrderDetailsContextFulfilmentExpressFulfilment {
  isExpressSlot: boolean;
  isLastExpressHourWindow: boolean;
}

export interface OrderDetailsContextFulfilment {
  address: string;
  areaId: number;
  expressFulfilment: OrderDetailsContextFulfilmentExpressFulfilment;
  fulfilmentStoreId: number;
  isAddressInDeliveryZone: boolean;
  isDefaultDeliveryAddress: boolean;
  isSlotToday: boolean;
  method: string;
  perishableCode: string;
  cutOffTime?: unknown;
  endTime?: unknown;
  locker?: unknown;
  selectedDate?: unknown;
  selectedDateWithTZInfo?: unknown;
  startTime?: unknown;
}

export interface OrderDetailsContextShopperOneCardBalance {
  isOneCardInError: boolean;
  oneCardCurrency: string;
  oneCardNumber: string;
  onecardPointsBalance: number;
  redeemableRewardVouchers: number;
  continuitySpend?: unknown;
}

export interface OrderDetailsContextShopper {
  firstName: string;
  hasActiveDeliverySubscription: boolean;
  hasOnecard: boolean;
  isChangingOrder: boolean;
  isLoggedIn: boolean;
  isPriorityShopper: boolean;
  isShopper: boolean;
  isSupplyLimitOverrideShopper: boolean;
  oneCardBalance: OrderDetailsContextShopperOneCardBalance;
  orderCount: string;
  sessionGroups: number[];
  shopperIdHash: string;
  shopperScvId: string;
  changingOrderId?: unknown;
}

export interface OrderDetailsContext {
  advancedSettingsResponse: OrderDetailsContextAdvancedSettingsResponse;
  basketTotals: OrderDetailsContextBasketTotals;
  enabledFeatures: string[];
  fulfilment: OrderDetailsContextFulfilment;
  shopper: OrderDetailsContextShopper;
  shoppingListItems: string[];
}

export interface OrderDetailsPartialFailures {
  breadcrumbGenerationFailed?: unknown;
  maxSupplyLimitFetchFailed?: unknown;
  productGroupFetchFailed?: unknown;
  productTagFetchFailed?: unknown;
  purchaseUnitFetchFailed?: unknown;
  shopperNotesFetchFailed?: unknown;
  targetOfferFetchFailed?: unknown;
  trolleyQuantityUpdateFailed?: unknown;
}

export interface OrderDetailsProductsItemImages {
  big: string;
  small: string;
}

export interface OrderDetailsProductsItemPrice {
  averagePricePerSingleUnit: number | null;
  canShowOriginalPrice: boolean;
  hasBonusPoints: boolean;
  isClubPrice: boolean;
  isNew: boolean;
  isSpecial: boolean;
  isTargetedOffer: boolean;
  originalPrice: number;
  salePrice: number;
  savePrice: number;
  discount?: unknown;
  purchasingUnitPrice?: unknown;
  total?: unknown;
}

export interface OrderDetailsProductsItemProductTagMultiBuy {
  link: string;
  quantity: number;
  value: number;
}

export interface OrderDetailsProductsItemProductTag {
  multiBuy: OrderDetailsProductsItemProductTagMultiBuy | null;
  tagType: string;
  additionalTag?: unknown;
  bonusPoints?: unknown;
  targetedOffer?: unknown;
}

export interface OrderDetailsProductsItemQuantity {
  increment: number;
  max: number;
  min: number;
  value: number | null;
  purchasingQuantityString?: unknown;
  quantityInOrder?: unknown;
}

export interface OrderDetailsProductsItemSize {
  cupMeasure: string | null;
  cupPrice: number;
  packageType: string | null;
  volumeSize: string | null;
}

export interface OrderDetailsProductsItem {
  averageWeightPerUnit: number | null;
  barcode: string;
  brand: string;
  hasShopperNotes: boolean;
  images: OrderDetailsProductsItemImages;
  name: string;
  price: OrderDetailsProductsItemPrice;
  productTag: OrderDetailsProductsItemProductTag | null;
  quantity: OrderDetailsProductsItemQuantity;
  selectedPurchasingUnit: string;
  size: OrderDetailsProductsItemSize;
  sku: string;
  slug: string;
  subsAllowed: boolean;
  supportsBothEachAndKgPricing: boolean;
  type: string;
  unit: string;
  variety: string | null;
  adId?: unknown;
  eachUnitQuantity?: unknown;
  priceUnitLabel?: unknown;
}

export interface OrderDetailsProducts {
  items: OrderDetailsProductsItem[];
  totalItems: number;
}

export interface OrderDetailsSortOption {
  selected: boolean;
  text: string;
  value: string;
}

export interface OrderDetails {
  breadcrumb: OrderDetailsBreadcrumb;
  context: OrderDetailsContext;
  currentPageSize: number;
  currentSortOption: string;
  dasFacets: Unknown[];
  facets: Unknown[];
  isSuccessful: boolean;
  partialFailures: OrderDetailsPartialFailures;
  products: OrderDetailsProducts;
  rootUrl: string;
  sortOptions: OrderDetailsSortOption[];
  action?: unknown;
  messages?: unknown;
  targetedOfferDetails?: unknown;
}
