// Code generated by jtd-codegen for TypeScript v0.2.1

export interface OrdersFilterList {
  selected: boolean;
  text: string;
  value: string;
}

export interface OrdersItem {
  deliveryFee: number;
  fulfilmentDate: string;
  fulfilmentTime: string;
  isEditable: boolean;
  method: string;
  orderDate: string;
  orderId: number;
  prefix: string;
  status: string;
  total: number;
}

export interface Orders {
  filterList: OrdersFilterList[];
  items: OrdersItem[];
  totalItems: number;
}
