// Code generated by jtd-codegen for TypeScript v0.2.1

export interface CartProductSaleType {
  minUnit: number;
  stepSize: number;
  type: string;
  unit: string;
}

export interface CartProduct {
  badgeImageUrl: string;
  catalogPrice: number;
  categoryName: string;
  hasBadge: boolean;
  imageUrl: string;
  liquor: boolean;
  name: string;
  price: number;
  productId: string;
  promoBadgeImageTitle: string;
  promotionCode: string;
  quantity: number;
  restricted: boolean;
  saleTypes: CartProductSaleType[];
  sale_type: string;
  tobacco: boolean;
  weightDisplayName: string;
  brand?: string;
  originStatement?: string;
  uom?: string;
}

export interface CartStore {
  storeAddress: string;
  storeId: string;
  storeName: string;
  storeRegion: string;
}

export interface Cart {
  allowSubstitutions: boolean;
  bagFee: number;
  orderNumber: number;
  products: CartProduct[];
  promoCodeDiscount: number;
  saving: number;
  serviceFee: number;
  store: CartStore;
  subtotal: number;
  unavailableProducts: CartProduct[];
  wasRepriced: boolean;
}
