// Code generated by jtd-codegen for TypeScript v0.2.1

interface BaseShoppingListItem {
  id: string;
  note: string | null;
  product_id: string;
  qu_id: string;
  row_created_timestamp: string;
  shopping_list_id: string;
}

export interface RawShoppingListItem extends BaseShoppingListItem {
  amount: string | number;
  done: string;
}

export interface ShoppingListItem extends BaseShoppingListItem {
  amount: number;
  done: boolean;
}

export interface NewShoppingListItem {
  amount: string;
  note?: string | null;
  product_id: string;
  qu_id: string;
  shopping_list_id: string;
}
