name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CACHE_DIR: "node_modules/.cache/test"
  COUNTDOWN_EMAIL: ${{ secrets.COUNTDOWN_EMAIL }}
  COUNTDOWN_PASSWORD: ${{ secrets.COUNTDOWN_PASSWORD }}
  GROCY_API_KEY: ${{ secrets.GROCY_API_KEY }}
  GROCY_URL: ${{ secrets.GROCY_URL }}
  GT_LOG_LEVEL: "INFO"
  PAKNSAVE_EMAIL: ${{ secrets.PAKNSAVE_EMAIL }}
  PAKNSAVE_PASSWORD: ${{ secrets.PAKNSAVE_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn run build -t prod

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: Build Output
          path: build/out


      - name: Typecheck
        run: yarn tsc

      - name: Lint
        run: yarn run lint

      - name: Test
        run: yarn run test:internal

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: Test Report
          path: build/test-report.html