# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CACHE_DIR: "node_modules/.cache/test"
  GT_LOG_LEVEL: "INFO"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn run build -t dev

      - name: Typecheck
        run: yarn run tsc

      - name: Lint
        run: yarn run lint

      - name: Setup for tests
        run: yarn playwright install-deps firefox

      - name: Test
        run: yarn run test
        timeout-minutes: 10
