# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CACHE_DIR: "node_modules/.cache/test"
  GT_LOG_LEVEL: "INFO"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - run: yarn install

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: yarn run build -t dev

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: yarn run tsc
      - run: yarn run lint
  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: yarn playwright install-deps firefox
      - run: yarn run test
